# Generated by Django 2.2 on 2020-03-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='totalcasesdata',
            options={'verbose_name_plural': 'TotalCases'},
        ),
    ]
