# Generated by Django 2.2 on 2020-03-25 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200324_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimatedTotalCasesData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_date', models.DateField()),
                ('estimated_total_cases', models.PositiveIntegerField()),
                ('estimated_new_cases', models.PositiveIntegerField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Country')),
            ],
            options={
                'verbose_name_plural': 'EstimatedTotalCases',
            },
        ),
    ]
