# Generated by Django 2.2 on 2020-03-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_estimatedtotalcasesdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(default='XX', max_length=3),
        ),
        migrations.AddField(
            model_name='country',
            name='continent_id',
            field=models.PositiveIntegerField(default=1, help_text='EUROPE-1,NORTH-AMERICA-2,ASIA-3,SOUTH-AMERICA-4'),
        ),
    ]
